### PR TITLE
Update .gitignore to exclude .vs folder

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
Hi @DevAffan ,

Thank you for your feedback! I appreciate your guidance regarding the .vs folder. 

I have updated the .gitignore file to exclude the .vs folder, ensuring a cleaner file structure.

Please check the repository at your convenience, and let me know if you encounter any further issues.

 I’m here to help and will address any additional concerns you might have.
Thanks in Advance ❤️🧑‍💻

### CODE REVIEW

**Review by DevAffan — CHANGES_REQUESTED** [review]
Hi,

It still shows a lot of .vs and other extraneous files, with over 1000 files queued for review. Please ensure that all the unnecessary folders and files are properly added to .gitignore. I recommend checking the "Changes" section in your VSCode editor before pushing it again.

Thank you!

**Comment by syedmaazsaeed** [comment]
Okay .

**Comment by syedmaazsaeed** [comment]
@DevAffan Now Check it Again.

**Comment by syedmaazsaeed** [comment]
Hi @DevAffan,

I have excluded the extra files and folders from the C# code and added the JavaScript code that I practiced. You can check the repository now to see the updates.

Thank you for your guidance, and if there are any further issues or suggestions, please let me know!

**Review by DevAffan — CHANGES_REQUESTED** [review]
It seems like you've placed the .gitignore file in the wrong location, which is why it's not preventing extra files from being pushed. Please move the .gitignore file to the root directory of your project. Currently, it's inside the .idea folder, which is incorrect.

**Comment by syedmaazsaeed** [comment]
Hi @DevAffan 

Yes, that was the issue. Sorry for the inconvenience! The .gitignore file was indeed placed in the wrong location. (.idea folder)

I have now moved it to the root directory of the project. Please check again and let me know if everything looks good.

**Pull request closed without merging**
